# Generated by Django 4.2 on 2025-01-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateField()),
                ('membershipStatus', models.CharField(max_length=50)),
                ('allotmentDate', models.DateField()),
                ('membershipType', models.CharField(max_length=50)),
                ('bookingPhase', models.CharField(max_length=50)),
                ('endDate', models.DateField()),
                ('bookingAgency', models.CharField(max_length=50)),
                ('isVerified', models.BooleanField()),
                ('isConstructed', models.BooleanField()),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plotNumber', models.CharField(max_length=50)),
                ('plotStreet', models.CharField(max_length=50)),
                ('plotBlock', models.CharField(max_length=50)),
                ('plotSize', models.CharField(max_length=50)),
                ('plotCategory', models.CharField(max_length=50)),
                ('extraFeatures', models.TextField()),
                ('extraLand', models.CharField(max_length=50)),
                ('is_possession', models.BooleanField()),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membership')),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.plot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userprofile')),
            ],
        ),
    ]
