# Generated by Django 4.2 on 2025-01-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='allotmentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='bookingAgency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='bookingDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='bookingPhase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isConstructed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plot',
            name='extraFeatures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='extraLand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='is_possession',
            field=models.BooleanField(default=False),
        ),
    ]
