# Generated by Django 4.2 on 2025-01-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membership_allotmentdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
