# Generated by Django 4.2 on 2025-01-11 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_owners'),
        ('membership', '0004_userattachment_membershipattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='Owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.owners'),
        ),
    ]
