# Generated by Django 4.2 on 2025-01-11 07:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_membership_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='plotSurronding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
