# Generated by Django 4.2 on 2025-01-11 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_plot_plotsurronding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarks',
            name='plot',
        ),
        migrations.AddField(
            model_name='remarks',
            name='membership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
            preserve_default=False,
        ),
    ]
