# Generated by Django 4.2 on 2025-01-11 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_owners'),
        ('membership', '0007_remove_remarks_plot_remarks_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentMethod', models.CharField(max_length=50)),
                ('paymentDate', models.DateTimeField()),
                ('paymentReceipt', models.FileField(upload_to='payment/')),
                ('paymentStatus', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('Owners', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.owners')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membership')),
                ('receviedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userprofile')),
            ],
        ),
    ]
